// src/app/components/PricingCard.tsx
import { motion } from 'motion/react';
import { Check, X, Crown } from 'lucide-react';

interface PricingCardProps {
  name: string;
  price: string;
  period: string;
  description: string;
  badge?: string;
  features: Array<{ text: string; included: boolean }>;
  cta: string;
  variant: 'free' | 'pro' | 'premium';
}

export default function PricingCard({
  name,
  price,
  period,
  description,
  badge,
  features,
  cta,
  variant,
}: PricingCardProps) {
  const variantStyles = {
    free: {
      bg: 'bg-card',
      border: 'border-border',
      buttonBg: 'bg-background hover:bg-primary hover:text-primary-foreground',
      buttonText: 'text-foreground',
    },
    pro: {
      bg: 'bg-accent',
      border: 'border-accent',
      buttonBg: 'bg-white hover:bg-primary',
      buttonText: 'text-accent hover:text-primary-foreground',
      scale: 1.05,
    },
    premium: {
      bg: 'bg-primary',
      border: 'border-primary',
      buttonBg: 'bg-white hover:bg-accent',
      buttonText: 'text-primary hover:text-accent-foreground',
    },
  };

  const style = variantStyles[variant];

  return (
    <motion.div
      whileHover={{ y: -8 }}
      className={`relative rounded-2xl p-8 border-2 ${style.bg} ${style.border} ${
        variant === 'pro' ? 'shadow-2xl shadow-accent/20 scale-105' : 'shadow-lg'
      } transition-all h-full flex flex-col`}
      style={{
        color: variant === 'pro' ? '#ffffff' : variant === 'premium' ? '#ffffff' : undefined,
      }}
    >
      {badge && (
        <div className="absolute -top-4 left-1/2 -translate-x-1/2 px-4 py-1.5 bg-white text-accent rounded-full text-sm font-semibold shadow-lg flex items-center gap-2">
          <Crown size={14} />
          {badge}
        </div>
      )}

      <div className="mb-8">
        <div className="text-sm font-semibold mb-2 opacity-90">{name}</div>
        <div className="flex items-end gap-1 mb-2">
          <span className="text-5xl" style={{ fontFamily: 'var(--font-display)' }}>
            {price}
          </span>
          <span className="text-lg opacity-70 mb-2">{period}</span>
        </div>
        <p className="opacity-80">{description}</p>
      </div>

      <div className="flex-1 mb-8">
        <ul className="space-y-3">
          {features.map((feature, index) => (
            <li key={index} className="flex items-start gap-3">
              {feature.included ? (
                <Check size={20} className="mt-0.5 flex-shrink-0" />
              ) : (
                <X size={20} className="mt-0.5 flex-shrink-0 opacity-30" />
              )}
              <span className={feature.included ? '' : 'opacity-50'}>{feature.text}</span>
            </li>
          ))}
        </ul>
      </div>

      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        className={`w-full py-4 rounded-full font-semibold transition-all ${style.buttonBg} ${style.buttonText}`}
      >
        {cta}
      </motion.button>
    </motion.div>
  );
}

// src/app/shared/components/pricing-card/pricing-card.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { NgClass } from '@angular/common';

export interface PricingFeature {
  text: string;
  included: boolean;
}

@Component({
  selector: 'app-pricing-card',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [ngClass]="cardClasses" class="relative rounded-2xl p-8 border-2 transition-all h-full flex flex-col hover:-translate-y-2 duration-300">

      @if (badge) {
        <div class="absolute -top-4 left-1/2 -translate-x-1/2 px-4 py-1.5 bg-white text-accent rounded-full text-sm font-semibold shadow-lg flex items-center gap-2">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="m2 4 3 12h14l3-12-6 5-4-5-4 5-6-5z"/>
            <path d="M5 20h14"/>
          </svg>
          {{ badge }}
        </div>
      }

      <div class="mb-8">
        <div class="text-sm font-semibold mb-2 opacity-90">{{ name }}</div>
        <div class="flex items-end gap-1 mb-2">
          <span class="text-5xl font-bold">{{ price }}</span>
          <span class="text-lg opacity-70 mb-2">{{ period }}</span>
        </div>
        <p class="opacity-80">{{ description }}</p>
      </div>

      <div class="flex-1 mb-8">
        <ul class="space-y-3">
          @for (feature of features; track $index) {
            <li class="flex items-start gap-3">
              @if (feature.included) {
                <svg class="mt-0.5 flex-shrink-0" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <polyline points="20 6 9 17 4 12"/>
                </svg>
              } @else {
                <svg class="mt-0.5 flex-shrink-0 opacity-30" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                </svg>
              }
              <span [class.opacity-50]="!feature.included">{{ feature.text }}</span>
            </li>
          }
        </ul>
      </div>

      <button [ngClass]="buttonClasses" class="w-full py-4 rounded-full font-semibold transition-all hover:scale-105 active:scale-95">
        {{ cta }}
      </button>

    </div>
  `
})
export class PricingCardComponent {
  @Input() name = '';
  @Input() price = '';
  @Input() period = '';
  @Input() description = '';
  @Input() badge = '';
  @Input() features: PricingFeature[] = [];
  @Input() cta = '';
  @Input() variant: 'free' | 'pro' | 'premium' = 'free';

  get cardClasses(): Record<string, boolean> {
    return {
      'bg-accent border-accent shadow-2xl text-white scale-105': this.variant === 'pro',
      'bg-primary border-primary shadow-lg text-white': this.variant === 'premium',
      'bg-card border-border shadow-lg': this.variant === 'free',
    };
  }

  get buttonClasses(): Record<string, boolean> {
    return {
      'bg-white text-accent hover:bg-primary hover:text-white': this.variant === 'pro',
      'bg-white text-primary hover:bg-accent hover:text-white': this.variant === 'premium',
      'bg-background border-2 border-border hover:bg-primary hover:text-primary-foreground': this.variant === 'free',
    };
  }
}
